version: '3.8'

services:
  server:
    container_name: pix-test_server
    build: .
    ports:
      - '3001:3001'
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/test_voltz
    networks:
      - my-network
  db:
    container_name: pix-test_database
    image: postgres:latest
    ports:
      - '5434:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'test_voltz'
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
