version: '3.5'

services:
  server:
    container_name: pix-test_server
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    ports:
      - '3016:3001'
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - db
  db:
    container_name: pix-test_database
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
    volumes:
      # - './doc/backup:/docker-entrypoint-initdb.d/up.sql'
      # - '/etc/backups/data-postgres/pix-test:/var/lib/postgresql/data'
      - ~/apps/postgres:/var/lib/postgresql/data
    restart: always
